spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

spring.datasource.url=jdbc:h2:file:~/mancalaak;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.settings.web-allow-others=true



#spring.datasource.initialization-mode=always
#javax.persistence.schema-generation.database.action=create
javax.persistence.schema-generation.database.action=drop-and-create
#javax.persistence.schema-generation.database.action=update
eclipselink.weaving=false


spring.main.allow-bean-definition-overriding=true
spring.jpa.show-sql=true
